### PR TITLE
Sort the report by class name.

### PR DESCRIPTION
**Pull request by HHest**
Perform a sort so that the report output is sorted by class names.

### CODE REVIEW

**Comment by ionelmc** [comment]
Can you take a look at the test failures?

I'm fine with dropping 2.6 support. 

Also, see #10.

**Comment by HHest** [comment]
Thank you. I am a bit confused about the test failures. It seems the test
is failing on the sample file you're using to generate nosetests failures,
in order to check how the html report behaves. Travis should not count
this, I think.

Am quite tempted to volunteer to be a maintainer, but I don't have much
experience with git and such. If you don't mind that, I will give it a try
:)

Thao

**Comment by ionelmc** [comment]
Fix the iteritems issues first (eg: https://travis-ci.org/ionelmc/nose-htmloutput/jobs/104030601#L260) and we'll see how Travis runs after that.

**Comment by HHest** [comment]
Now I'm using items instead of iteritems. All nocover tests for python 2.7+ pass now.

**Comment by HHest** [comment]
After updating my pull request to include your change in tox.ini, and removing the python 2.6 tests, the patch passes everything. Thanks.

**Comment by ionelmc** [comment]
Thanks.

**Pull request merged**
